import { CollectionCreateSchema } from "typesense/src/Typesense/Collections";

/**
 * General-purpose document chunk schema.
 * Each document represents a single article or paragraph extracted from a
 * larger source (page, file, confluence article, etc.).
 */
export const docChunksSchema: CollectionCreateSchema = {
    name: "doc_chunks",
    fields: [
        // --- Identity ---
        // Zero-based position of this chunk within the source document.
        // Calculated per document during parsing.
        { name: "chunk_index",     type: "int32",     index: false },

        // --- Content ---
        // Top-level heading (`#`) of a Markdown document,
        // or the document title for non-Markdown sources.
        { name: "title",           type: "string"    },
        // Heading of the section this chunk belongs to (e.g. `##` in Markdown).
        { name: "section_heading", type: "string",    optional: true },
        // Raw content of the section (in case of Markdown, the original MD text).
        { name: "content",         type: "string"    },

        // --- Classification ---
        // Top-level category used to group and filter documents.
        { name: "category",        type: "string",    facet: true },
        // Optional secondary classification within a category.
        { name: "subcategory",     type: "string",    facet: true, optional: true },
        // Free-form labels for cross-cutting topics. Extracted by an LLM.
        { name: "tags",            type: "string[]",  facet: true },

        // --- Navigation ---
        // URL-safe slug identifying this chunk.
        // Format: `{source_type}-{source}-{document_path}-{chunk_index}`
        { name: "slug",            type: "string",    index: false },
        // Importance score derived from documentation tree depth and
        // section heading level. Lower values = higher priority.
        { name: "weight",          type: "int32", facet: true},

        // --- Source tracing ---
        // Path to the original document.
        // For git repos: `github.com/org/repo/path/to/file.md`
        // For local files, Confluence, Google Docs, etc.: the document path.
        { name: "source",          type: "string",    facet: true },
        // Origin platform of the document.
        // e.g. "github", "gitlab", "confluence", "google-docs", "local"
        { name: "source_type",          type: "string",    facet: true },

        // --- Vector embedding (auto-generated by Typesense built-in model) ---
        {
            name: "embedding",
            type: "float[]",
            embed: {
                from: ["title", "content"],
                model_config: { model_name: "ts/e5-small" },
            },
        },
    ],
    default_sorting_field: "weight",
}

export const schemas: CollectionCreateSchema[] = [docChunksSchema]
