import { CollectionCreateSchema } from "typesense/src/Typesense/Collections";

/**
 * General-purpose document chunk schema.
 * Each document represents a single article or paragraph extracted from a
 * larger source (page, file, confluence article, etc.).
 */
export const docChunksSchema: CollectionCreateSchema = {
    name: "doc_chunks",
    fields: [
        // --- Identity ---
        { name: "id",              type: "string"    },
        { name: "document_id",     type: "string"    },
        { name: "chunk_index",     type: "int32"     },

        // --- Content ---
        { name: "title",           type: "string"    },
        { name: "section_heading", type: "string",    optional: true },
        { name: "content",         type: "string"    },

        // --- Classification ---
        { name: "category",        type: "string",    facet: true },
        { name: "subcategory",     type: "string",    facet: true, optional: true },
        { name: "tags",            type: "string[]",  facet: true },

        // --- Navigation ---
        { name: "slug",            type: "string"    },
        { name: "weight",          type: "int32"     },

        // --- Source tracing ---
        { name: "source",          type: "string",    facet: true },
        { name: "source_type",          type: "string",    facet: true },

        // --- Vector embedding (auto-generated by Typesense built-in model) ---
        {
            name: "embedding",
            type: "float[]",
            embed: {
                from: ["title", "content"],
                model_config: { model_name: "ts/e5-small" },
            },
        },
    ],
    default_sorting_field: "weight",
}

export const schemas: CollectionCreateSchema[] = [docChunksSchema]
